basePath: /
definitions:
  completions.CalculateHideScore:
    properties:
      document_length:
        description: 文档长度
        type: integer
      is_whitespace_after_cursor:
        description: 光标之后该行是否没有内容(空白除外)
        type: boolean
      prefix:
        description: 光标前的所有内容
        type: string
      previous_label:
        description: 上个请求是否被接受
        type: integer
      previous_label_timestamp:
        description: 上个请求被接受的时间戳
        type: integer
      prompt_end_pos:
        description: 光标在文档中的偏移
        type: integer
    type: object
  completions.CompletionChoice:
    properties:
      text:
        type: string
    type: object
  completions.CompletionPerformance:
    properties:
      completion_tokens:
        type: integer
      context_duration:
        description: 获取上下文的时长(毫秒)
        type: integer
      llm_duration:
        description: 调用大语言模型耗用的时长(毫秒)
        type: integer
      prompt_tokens:
        type: integer
      queue_duration:
        description: 排队时长(毫秒)
        type: integer
      receive_time:
        description: 收到请求的时间
        type: string
      total_duration:
        description: 总时长(毫秒)
        type: integer
      total_tokens:
        type: integer
    type: object
  completions.CompletionRequest:
    properties:
      beta_mode:
        type: boolean
      calculate_hide_score:
        $ref: '#/definitions/completions.CalculateHideScore'
      client_id:
        type: string
      completion_id:
        type: string
      extra:
        additionalProperties: true
        type: object
      file_project_path:
        type: string
      import_content:
        type: string
      language_id:
        type: string
      model:
        type: string
      parent_id:
        type: string
      project_path:
        type: string
      prompt:
        type: string
      prompt_options:
        $ref: '#/definitions/completions.PromptOptions'
      stop:
        items:
          type: string
        type: array
      temperature:
        type: number
      trigger_mode:
        type: string
      verbose:
        type: boolean
    type: object
  completions.CompletionResponse:
    properties:
      choices:
        items:
          $ref: '#/definitions/completions.CompletionChoice'
        type: array
      created:
        type: integer
      error:
        type: string
      id:
        type: string
      model:
        type: string
      object:
        type: string
      status:
        $ref: '#/definitions/model.CompletionStatus'
      usage:
        $ref: '#/definitions/completions.CompletionPerformance'
      verbose:
        $ref: '#/definitions/model.CompletionVerbose'
    type: object
  completions.PromptOptions:
    properties:
      code_context:
        type: string
      cursor_line_prefix:
        type: string
      cursor_line_suffix:
        type: string
      prefix:
        type: string
      suffix:
        type: string
    type: object
  model.CompletionParameter:
    properties:
      clientID:
        description: 用户ID，唯一标识发起补全请求的用户
        type: string
      completionID:
        description: 补全请求ID，用于唯一标识一次补全请求
        type: string
      context:
        description: 上下文
        type: string
      max_tokens:
        description: 回复内容的最大token数
        type: integer
      model:
        description: 模型
        type: string
      prefix:
        description: 前缀
        type: string
      stop:
        description: 停止符
        items:
          type: string
        type: array
      suffix:
        description: 后缀
        type: string
      temperature:
        description: 温度
        type: number
      verbose:
        description: 是否需要更详细的回复，帮助调试
        type: boolean
    type: object
  model.CompletionStatus:
    enum:
    - success
    - reqError
    - serverError
    - modelError
    - empty
    - rejected
    - timeout
    - canceled
    - busy
    type: string
    x-enum-comments:
      StatusBusy: 服务端繁忙
      StatusCanceled: 用户取消
      StatusEmpty: 补全结果为空
      StatusModelError: 模型响应错误
      StatusRejected: 根据规则拒绝补全
      StatusReqError: 请求存在错误
      StatusServerError: 服务端错误
      StatusSuccess: 补全成功
      StatusTimeout: 补全请求超时
    x-enum-descriptions:
    - 补全成功
    - 请求存在错误
    - 服务端错误
    - 模型响应错误
    - 补全结果为空
    - 根据规则拒绝补全
    - 补全请求超时
    - 用户取消
    - 服务端繁忙
    x-enum-varnames:
    - StatusSuccess
    - StatusReqError
    - StatusServerError
    - StatusModelError
    - StatusEmpty
    - StatusRejected
    - StatusTimeout
    - StatusCanceled
    - StatusBusy
  model.CompletionVerbose:
    properties:
      id:
        type: string
      input:
        additionalProperties: true
        type: object
      output:
        additionalProperties: true
        type: object
    type: object
  server.LogSettings:
    properties:
      level:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a code completion service API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Code Completions API
  version: "1.0"
paths:
  /api/completions:
    post:
      consumes:
      - application/json
      description: 根据提供的代码上下文生成代码补全建议（OPENAI协议的请求格式）
      parameters:
      - description: 补全请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CompletionParameter'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/completions.CompletionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/completions.CompletionResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/completions.CompletionResponse'
      summary: openai/completions接口的代码补全
      tags:
      - completions
  /api/details:
    get:
      consumes:
      - application/json
      description: 获取代码补全服务的详细信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取详细信息
      tags:
      - debug
  /api/logs:
    post:
      consumes:
      - application/json
      description: 设置应用程序的日志级别
      parameters:
      - description: 日志级别设置
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/server.LogSettings'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: 设置日志级别
      tags:
      - debug
  /api/stats:
    get:
      consumes:
      - application/json
      description: 获取代码补全服务的统计信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取统计信息
      tags:
      - debug
  /code-completion/api/v1/completions:
    post:
      consumes:
      - application/json
      description: 根据提供的代码上下文生成代码补全建议
      parameters:
      - description: 补全请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/completions.CompletionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/completions.CompletionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/completions.CompletionResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/completions.CompletionResponse'
      summary: 兼容千流补全接口的代码补全
      tags:
      - completions
  /code-completion/api/v2/completions:
    post:
      consumes:
      - application/json
      description: 根据提供的代码上下文生成代码补全建议，该接口使用sangfor/completions接口，请求参数在客户端已经被预处理过了
      parameters:
      - description: 补全请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CompletionParameter'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/completions.CompletionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/completions.CompletionResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/completions.CompletionResponse'
      summary: sangfor/completions接口的代码补全
      tags:
      - completions
  /healthz:
    get:
      consumes:
      - application/json
      description: 检查服务是否正常运行
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 健康检查
      tags:
      - health
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
